from flask import Flask, render_template, request, flash, redirect, url_for
import subprocess
import os

app = Flask(__name__)
# flash 메시지 기능을 사용하기 위한 시크릿 키
app.config['SECRET_KEY'] = 'a-very-secret-key-that-should-be-changed'

# Kickstart 템플릿
KS_TEMPLATE = """
# Kickstart file for RHEL 9.6 Bastion VM - Generated by WebUI
lang en_US.UTF-8
keyboard --xlayouts='us'
timezone Asia/Seoul --isUtc
rootpw --plaintext ##ROOT_PASSWORD##
url --url="http://##HTTP_SERVER_IP##/rhel9.6"
network --bootproto=static --device=eth0 --ip=##IP_ADDRESS## --netmask=##SUBNET## --gateway=192.168.0.1 --nameserver=8.8.8.8,8.8.4.4 --hostname=##HOSTNAME## --activate
services --enabled="chronyd,httpd,named"
firewall --enabled --service=ssh,http,https
bootloader --location=mbr --boot-drive=vda
zerombr
clearpart --all --initlabel
autopart --type=lvm
graphical

%packages
@^server-with-gui
haproxy
bind
bind-utils
chrony
httpd
httpd-tools
python3
python3-pip
ansible-core
%end

%post --log=/root/ks-post.log
pip3 install Flask Flask-WTF
%end

reboot
"""

@app.route('/', methods=['GET', 'POST'])
def index():
    if request.method == 'POST':
        action = request.form.get('action')
        try:
            if action == 'generate_kickstart':
                ks_content = KS_TEMPLATE.replace("##ROOT_PASSWORD##", request.form.get('root_password')) \
                                        .replace("##HTTP_SERVER_IP##", request.form.get('http_server_ip')) \
                                        .replace("##IP_ADDRESS##", request.form.get('ip_address')) \
                                        .replace("##SUBNET##", request.form.get('subnet')) \
                                        .replace("##HOSTNAME##", request.form.get('hostname'))

                ks_path = "/var/www/html/kickstart/ks.cfg"
                with open(ks_path, "w") as f:
                    f.write(ks_content)
                
                # SELinux 컨텍스트 복원
                subprocess.run(['sudo', 'restorecon', '-v', ks_path], check=True)
                flash(f"✅ Kickstart 파일이 {ks_path} 에 성공적으로 생성되었습니다.", 'success')

            elif action == 'download_iso':
                # AlmaLinux 9.4를 예시로 사용 (RHEL 정식 ISO는 구독 필요)
                iso_url = "https://repo.almalinux.org/almalinux/9.4/isos/x86_64/AlmaLinux-9.4-x86_64-dvd.iso"
                iso_name = os.path.basename(iso_url)
                download_path = f"/tmp/{iso_name}"
                mount_path = "/var/www/html/rhel9.6"

                flash(f"ISO 다운로드를 시작합니다... (대상: {mount_path})", 'info')
                
                # wget과 mount 실행
                subprocess.run(['sudo', 'wget', '-O', download_path, iso_url], check=True)
                subprocess.run(['sudo', 'mount', '-o', 'loop', download_path, mount_path], check=True)
                
                flash(f"✅ ISO 이미지를 성공적으로 다운로드하고 {mount_path} 에 마운트했습니다.", 'success')
            
            elif action == 'create_vm':
                http_server_ip = request.form.get('http_server_ip')
                ks_url = f"ks=http://{http_server_ip}/kickstart/ks.cfg"
                location_url = f"http://{http_server_ip}/rhel9.6"

                virt_install_cmd = [
                    'sudo', 'virt-install',
                    '--name', 'rhel96-bastion',
                    '--ram', '16384',
                    '--vcpus', '8',
                    '--disk', 'path=/var/lib/libvirt/images/rhel96-bastion.qcow2,size=50',
                    '--os-variant', 'rhel9.6',
                    '--network', 'bridge=virbr0',
                    '--graphics', 'vnc,listen=0.0.0.0',
                    '--location', location_url,
                    '--extra-args', ks_url,
                    '--noautoconsole'
                ]
                
                subprocess.run(virt_install_cmd, check=True)
                flash("🚀 VM 생성 명령을 실행했습니다. `virt-manager` 또는 `virsh list`로 상태를 확인하세요.", 'success')

        except Exception as e:
            flash(f"❌ 오류 발생: {e}", 'danger')

        return redirect(url_for('index'))

    return render_template('index.html')

if __name__ == '__main__':
    # 경고: 운영 환경에서는 debug=True 옵션을 사용하지 마세요.
    app.run(host='0.0.0.0', port=5000, debug=True)
